{"text": "In session 10.3, when creating the virtual environment with pipenv and trying to run the script gateway.py, you might get this error:\nTypeError: Descriptors cannot not be created directly.\nIf this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.\nIf you cannot immediately regenerate your protos, some other possible workarounds are:\n1. Downgrade the protobuf package to 3.20.x or lower.\n2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).\nMore information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates\nThis will happen if your version of protobuf is one of the newer ones. As a workaround, you can fix the protobuf version to an older one. In my case I got around the issue by creating the environment with:\npipenv install --python 3.9.13 requests grpcio==1.42.0 flask gunicorn \\\nkeras-image-helper tensorflow-protobuf==2.7.0 protobuf==3.19.6\nAdded by \u00c1ngel de Vicente", "section": "10. Kubernetes and TensorFlow Serving", "question": "Problem with recent version of protobuf", "course": "machine-learning-zoomcamp", "document_id": "727238ee"}