{"text": "Problem: when running the preprocess_data.py file you get the following error:\n\nwandb: ERROR api_key not configured (no-tty). call wandb.login(key=[your_api_key])\nSolution: Go to your WandB profile (top RHS) \u2192 user settings \u2192 scroll down to \u201cDanger Zone\u201d and copy your API key. \n\nThen before running preprocess_data.py, add and run the following cell in your notebook:\n\n%%bash\n\nWandb login <YOUR_API_KEY_HERE>.\nAdded and Answered by James Gammerman (jgammerman@gmail.com)", "section": "Module 2: Experiment tracking", "question": "WandB API error", "course": "mlops-zoomcamp", "document_id": "0f08bec7"}