{"text": "Problem: When running prepare.py getting KeyError: \u2018content-length\u2019\nSolution: From Emeli Dral:\nIt seems to me that the link we used in prepare.py to download taxi data does not work anymore. I substituted the instruction:\nurl = f\"https://nyc-tlc.s3.amazonaws.com/trip+data/{file}\nby the\nurl = f\"https://d37ci6vzurychx.cloudfront.net/trip-data/{file}\"\nin the prepare.py and it worked for me. Hopefully, if you do the same you will be able to get those data.", "section": "Module 5: Monitoring", "question": "KeyError \u2018content-length\u2019 when running prepare.py", "course": "mlops-zoomcamp", "document_id": "f33fc6e9"}